### ISSUE TITLE
Error if the header row contains merged cells

### ISSUE THREAD

**Issue by simonnjwalker** [simonnjwalker/ExcelToData#4]
This is the error message:

Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in ExcelToData.dll: 'Object reference not set to an instance of an object.'
   at Seamlex.Utilities.ExcelToData.IsValidWorksheetName(String testName) in ..\ExcelToData.cs:line 1218
   at Seamlex.Utilities.ExcelToData.ToDataSet(Byte[] byteArray, ExcelToDataOptions handlerOptions) in ..\ExcelToData.cs:line 1076
   at Seamlex.Utilities.ExcelToData.ToDataSet(String filePath, ExcelToDataOptions handlerOptions) in ..\ExcelToData.cs:line 1009
   at Seamlex.Utilities.ExcelToData.ToDataSet(String filePath) in ..\ExcelToData.cs:line 998

It appears likely that this or a similar issue will arise whenever the top row contains blank, invalid, and/or duplicated names.

**Comment by simonnjwalker** [comment]
Fixed in 1.0.2.  Duplicated and blank (including merged) column headers are ignored by default.
